# Generated by Django 2.2.6 on 2019-10-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taluka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Candidatedata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(max_length=200)),
                ('Party', models.CharField(max_length=200)),
                ('Votes', models.IntegerField()),
                ('Per_Votes', models.IntegerField()),
                ('taluka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guj.Taluka')),
            ],
        ),
    ]
