# Generated by Django 2.2.6 on 2019-10-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guj', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatedata',
            old_name='taluka',
            new_name='taluka_id',
        ),
        migrations.RenameField(
            model_name='taluka',
            old_name='T_name',
            new_name='taluka_id',
        ),
        migrations.AlterField(
            model_name='candidatedata',
            name='Per_Votes',
            field=models.CharField(max_length=100),
        ),
    ]
