# Generated by Django 2.2.6 on 2019-10-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guj', '0002_auto_20191018_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedata',
            name='taluka_id',
        ),
        migrations.DeleteModel(
            name='Taluka',
        ),
    ]
