# Generated by Django 2.2.7 on 2019-11-18 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guj', '0004_amreli_lathi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Party', models.CharField(max_length=200)),
                ('Seats_Won', models.CharField(max_length=200)),
            ],
        ),
    ]
