# Generated by Django 2.2.7 on 2019-11-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guj', '0005_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amreli_compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(max_length=200)),
                ('Party', models.CharField(max_length=200)),
                ('Votes', models.IntegerField()),
                ('Per_Votes', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dhari_compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(max_length=200)),
                ('Party', models.CharField(max_length=200)),
                ('Votes', models.IntegerField()),
                ('Per_Votes', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lathi_compare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Candidate', models.CharField(max_length=200)),
                ('Party', models.CharField(max_length=200)),
                ('Votes', models.IntegerField()),
                ('Per_Votes', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
